[package]
name = "augh"
version = "0.1.1"
edition = "2021"
description = "Panic but renamed augh"
license = "MIT OR Apache-2.0"
repository = "https://github.com/the-emerald/augh"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
